TimeStamp: "2020-07-16 10:23:19"
Username: "zhengteshuai"
BasicInfo:
   RealName: "zheng"
   Age: "18"
   Language:
   - "Golang"
   - "Python"
   - "PHP"
   Married: false

Hobby:
  Sport:
  - "Lure"
  - "basketball"
  Music:
  - "Hipop"
  LuckyNumber: 22